apiVersion: 1

datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse-crypto
    access: proxy
    isDefault: true
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      defaultDatabase: crypto
      username: default
    secureJsonData:
      password: ""
    editable: true
